In [1]:
import json
import pandas as pd

# ../../data/tmap_puzzle_car.json 읽기
with open('../../data/tmap_puzzle_get-off.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [2]:
'''
df를 DataFrame으로 변환

DataFrame의 각 열은 다음과 같음:
- subwayLine : api_response의 contents의 subwayLine 값
- stationName: api_response의 contents의 stationName 값
- stationCode: api_response의 contents의 stationCode 값
- updnLine : api_response의 contents의 stat의 updnLine 값
- dow: api_response의 contents의 stat의 i번째의 data의 dow 값
- hh : api_response의 contents의 stat의 i번째의 data의 hh 값
- mm : api_response의 contents의 stat의 i번째의 data의 mm 값
- getOffCarRate : api_response의 contents의 stat의 i번째의 data의 getOffCarRate 값
- prevStationName : api_response의 contents의 stat의 prevStationName 값
- prevStationCode : api_response의 contents의 stat의 prevStationCode 값
- startStationName : api_response의 contents의 stat의 startStationName 값
- startStationCode : api_response의 contents의 stat의 startStationCode 값
- endStationName : api_response의 contents의 stat의 endStationName 값
- endStationCode : api_response의 contents의 stat의 endStationCode 값
- statStartDate : api_response의 contents의 statStartDate 값
- statEndDate : api_response의 contents의 statEndDate 값
'''


records = []

for entry in data:
    contents = entry['api_response']['contents']
    subway_line = contents['subwayLine']
    station_name = contents['stationName']
    station_code = contents['stationCode']
    stat_start_date = contents['statStartDate']
    stat_end_date = contents['statEndDate']
    
    for stat in contents['stat']:
        updn_line = stat['updnLine']
        prev_station_code = stat['prevStationCode']
        prev_station_name = stat['prevStationName']
        start_station_code = stat['startStationCode']
        start_station_name = stat['startStationName']
        end_station_code = stat['endStationCode']
        end_station_name = stat['endStationName']
        
        for data_point in stat['data']:
            record = {
                'subwayLine': subway_line,
                'stationName': station_name,
                'stationCode': station_code,
                'updnLine': updn_line,
                'dow': data_point['dow'],
                'hh': data_point['hh'],
                'mm': data_point['mm'],
                'getOffCarRate': data_point['getOffCarRate'],
                'prevStationName': prev_station_name,
                'prevStationCode': prev_station_code,
                'startStationName': start_station_name,
                'startStationCode': start_station_code,
                'endStationName': end_station_name,
                'endStationCode': end_station_code,
                'statStartDate': stat_start_date,
                'statEndDate': stat_end_date
            }
            records.append(record)
df = pd.DataFrame.from_records(records)

In [3]:
# df csv로 저장
df.to_csv('../../data/tmap_puzzle_get-off.csv', index=False, encoding='utf-8-sig')
df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,getOffCarRate,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
0,2호선,강남역,222,0,MON,17,00,"[5, 6, 8, 16, 18, 13, 13, 8, 9, 5]",교대역,223,홍대입구역,239,성수역,211-R,20251026,20260125
1,2호선,강남역,222,0,MON,17,10,"[5, 7, 7, 16, 18, 14, 12, 9, 8, 5]",교대역,223,홍대입구역,239,성수역,211-R,20251026,20260125
2,2호선,강남역,222,0,MON,17,20,"[5, 7, 8, 15, 17, 14, 13, 9, 8, 5]",교대역,223,홍대입구역,239,성수역,211-R,20251026,20260125
3,2호선,강남역,222,0,MON,17,30,"[5, 6, 9, 14, 17, 14, 13, 8, 8, 5]",교대역,223,홍대입구역,239,성수역,211-R,20251026,20260125
4,2호선,강남역,222,0,MON,17,40,"[4, 7, 9, 14, 18, 14, 13, 8, 8, 5]",교대역,223,홍대입구역,239,성수역,211-R,20251026,20260125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18553,7호선,보라매역,742,1,SUN,19,10,"[6, 7, 10, 12, 15, 15, 16, 19]",신대방삼거리역,741,내방역,735,석남역,761,20251026,20260125
18554,7호선,보라매역,742,1,SUN,19,20,"[6, 7, 10, 12, 15, 15, 16, 19]",신대방삼거리역,741,내방역,735,석남역,761,20251026,20260125
18555,7호선,보라매역,742,1,SUN,19,30,"[6, 7, 10, 12, 15, 15, 16, 19]",신대방삼거리역,741,내방역,735,석남역,761,20251026,20260125
18556,7호선,보라매역,742,1,SUN,19,40,"[6, 7, 10, 12, 15, 15, 16, 19]",신대방삼거리역,741,내방역,735,석남역,761,20251026,20260125
18557,7호선,보라매역,742,1,SUN,19,50,"[6, 7, 10, 12, 15, 15, 16, 19]",신대방삼거리역,741,내방역,735,석남역,761,20251026,20260125

In [4]:
'''
stationCode=222, updnline=1, dow=MON, hh=18, mm=00 필터링
'''
filtered_df = df[
    (df['subwayLine'] == '2호선') &
    # (df['stationCode'] == '222') &
    (df['updnLine'] == 1) &
    (df['startStationName'] == '삼성역')
    # (df['dow'] == 'MON') &
    # (df['hh'] == '18') &
    # (df['mm'] == '00')
]
filtered_df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,getOffCarRate,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
90,2호선,강남역,222,1,MON,17,00,"[5, 9, 11, 16, 12, 15, 12, 8, 7, 5]",역삼역,221,삼성역,219,성수역,211-R,20251026,20260125
91,2호선,강남역,222,1,MON,17,10,"[6, 10, 11, 16, 12, 15, 12, 7, 7, 5]",역삼역,221,삼성역,219,성수역,211-R,20251026,20260125
92,2호선,강남역,222,1,MON,17,20,"[5, 11, 10, 15, 12, 15, 13, 8, 7, 5]",역삼역,221,삼성역,219,성수역,211-R,20251026,20260125
93,2호선,강남역,222,1,MON,17,30,"[6, 10, 10, 15, 11, 16, 13, 8, 7, 5]",역삼역,221,삼성역,219,성수역,211-R,20251026,20260125
94,2호선,강남역,222,1,MON,17,40,"[6, 10, 10, 14, 11, 15, 14, 7, 7, 5]",역삼역,221,삼성역,219,성수역,211-R,20251026,20260125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7099,2호선,선릉역,220,1,SUN,19,10,"[5, 9, 11, 12, 14, 15, 12, 9, 8, 5]",삼성역,219,삼성역,219,성수역,211-R,20251026,20260125
7100,2호선,선릉역,220,1,SUN,19,20,"[5, 9, 11, 12, 14, 15, 12, 9, 8, 5]",삼성역,219,삼성역,219,성수역,211-R,20251026,20260125
7101,2호선,선릉역,220,1,SUN,19,30,"[5, 9, 11, 12, 14, 15, 12, 9, 8, 5]",삼성역,219,삼성역,219,성수역,211-R,20251026,20260125
7102,2호선,선릉역,220,1,SUN,19,40,"[5, 9, 11, 12, 14, 15, 12, 9, 8, 5]",삼성역,219,삼성역,219,성수역,211-R,20251026,20260125
7103,2호선,선릉역,220,1,SUN,19,50,"[5, 9, 11, 12, 14, 15, 12, 9, 8, 5]",삼성역,219,삼성역,219,성수역,211-R,20251026,20260125

In [5]:
'''
df에서 df['subwayLine'] == '2호선'일때, (df['updnLine'] == 1) & (df['endStationName'] != '서울대입구역')만 남기기
df에서 df['subwayLine'] == '7호선'일때, (df['updnLine'] == 1) & ((df['endStationName'] != '신풍역')| (df['startStationName'] != '신풍역'))만 남기기
'''
scenario_df = df[(df['updnLine'] == 1)]
scenario_df = scenario_df[
    ~(
        ((df['subwayLine'] == '2호선') & (df['updnLine'] == 1) & ((df['endStationName'] == '서울대입구역') | (df['startStationName'] == '삼성역') | (df['endStationName'] == '삼성역'))) |
        ((df['subwayLine'] == '7호선') & (df['updnLine'] == 1) & ((df['endStationName'] == '신풍역') | (df['startStationName'] == '신풍역')))
    )
]
scenario_df

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_25528\1739569272.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  scenario_df = scenario_df[

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,getOffCarRate,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
24,2호선,강남역,222,1,MON,17,00,"[5, 9, 11, 16, 12, 15, 12, 8, 7, 5]",역삼역,221,성수역,211,신도림역,234,20251026,20260125
25,2호선,강남역,222,1,MON,17,10,"[6, 10, 11, 16, 12, 15, 12, 7, 7, 5]",역삼역,221,성수역,211,신도림역,234,20251026,20260125
26,2호선,강남역,222,1,MON,17,20,"[5, 11, 10, 15, 12, 15, 13, 8, 7, 5]",역삼역,221,성수역,211,신도림역,234,20251026,20260125
27,2호선,강남역,222,1,MON,17,30,"[6, 10, 10, 15, 11, 16, 13, 8, 7, 5]",역삼역,221,성수역,211,신도림역,234,20251026,20260125
28,2호선,강남역,222,1,MON,17,40,"[6, 10, 10, 14, 11, 15, 14, 7, 7, 5]",역삼역,221,성수역,211,신도림역,234,20251026,20260125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18553,7호선,보라매역,742,1,SUN,19,10,"[6, 7, 10, 12, 15, 15, 16, 19]",신대방삼거리역,741,내방역,735,석남역,761,20251026,20260125
18554,7호선,보라매역,742,1,SUN,19,20,"[6, 7, 10, 12, 15, 15, 16, 19]",신대방삼거리역,741,내방역,735,석남역,761,20251026,20260125
18555,7호선,보라매역,742,1,SUN,19,30,"[6, 7, 10, 12, 15, 15, 16, 19]",신대방삼거리역,741,내방역,735,석남역,761,20251026,20260125
18556,7호선,보라매역,742,1,SUN,19,40,"[6, 7, 10, 12, 15, 15, 16, 19]",신대방삼거리역,741,내방역,735,석남역,761,20251026,20260125
18557,7호선,보라매역,742,1,SUN,19,50,"[6, 7, 10, 12, 15, 15, 16, 19]",신대방삼거리역,741,내방역,735,석남역,761,20251026,20260125

In [6]:
scenario_df.to_csv('../../data/tmap_puzzle_filtering_get-off.csv', index=False, encoding='utf-8-sig')