In [1]:
import json
import pandas as pd

# ../../data/tmap_puzzle_car.json 읽기
with open('../../data/tmap_puzzle_car.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [2]:
'''
df를 DataFrame으로 변환

DataFrame의 각 열은 다음과 같음:
- subwayLine : api_response의 contents의 subwayLine 값
- stationName: api_response의 contents의 stationName 값
- stationCode: api_response의 contents의 stationCode 값
- updnLine : api_response의 contents의 stat의 updnLine 값
- dow: api_response의 contents의 stat의 i번째의 data의 dow 값
- hh : api_response의 contents의 stat의 i번째의 data의 hh 값
- mm : api_response의 contents의 stat의 i번째의 data의 mm 값
- congestionCar : api_response의 contents의 stat의 i번째의 data의 congestionCar 값
- prevStationName : api_response의 contents의 stat의 prevStationName 값
- prevStationCode : api_response의 contents의 stat의 prevStationCode 값
- startStationName : api_response의 contents의 stat의 startStationName 값
- startStationCode : api_response의 contents의 stat의 startStationCode 값
- endStationName : api_response의 contents의 stat의 endStationName 값
- endStationCode : api_response의 contents의 stat의 endStationCode 값
- statStartDate : api_response의 contents의 statStartDate 값
- statEndDate : api_response의 contents의 statEndDate 값
'''


records = []

for entry in data:
    contents = entry['api_response']['contents']
    subway_line = contents['subwayLine']
    station_name = contents['stationName']
    station_code = contents['stationCode']
    stat_start_date = contents['statStartDate']
    stat_end_date = contents['statEndDate']
    
    for stat in contents['stat']:
        updn_line = stat['updnLine']
        prev_station_code = stat['prevStationCode']
        prev_station_name = stat['prevStationName']
        start_station_code = stat['startStationCode']
        start_station_name = stat['startStationName']
        end_station_code = stat['endStationCode']
        end_station_name = stat['endStationName']
        
        for data_point in stat['data']:
            record = {
                'subwayLine': subway_line,
                'stationName': station_name,
                'stationCode': station_code,
                'updnLine': updn_line,
                'dow': data_point['dow'],
                'hh': data_point['hh'],
                'mm': data_point['mm'],
                'congestionCar': data_point['congestionCar'],
                'prevStationName': prev_station_name,
                'prevStationCode': prev_station_code,
                'startStationName': start_station_name,
                'startStationCode': start_station_code,
                'endStationName': end_station_name,
                'endStationCode': end_station_code,
                'statStartDate': stat_start_date,
                'statEndDate': stat_end_date
            }
            records.append(record)
df = pd.DataFrame.from_records(records)

In [3]:
# df csv로 저장
# df.to_csv('../../data/tmap_puzzle_car.csv', index=False, encoding='utf-8-sig')
df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,congestionCar,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
0,2호선,강남역,222,0,MON,17,00,"[32, 44, 37, 51, 45, 52, 42, 33, 33, 22]",교대역,223,을지로입구역,202,성수역,211,20251026,20260125
1,2호선,강남역,222,0,MON,17,10,"[34, 33, 43, 46, 45, 40, 47, 42, 28, 23]",교대역,223,을지로입구역,202,성수역,211,20251026,20260125
2,2호선,강남역,222,0,MON,17,20,"[30, 41, 37, 44, 50, 43, 42, 39, 32, 21]",교대역,223,을지로입구역,202,성수역,211,20251026,20260125
3,2호선,강남역,222,0,MON,17,30,"[41, 42, 39, 64, 51, 51, 51, 47, 28, 25]",교대역,223,을지로입구역,202,성수역,211,20251026,20260125
4,2호선,강남역,222,0,MON,17,40,"[39, 44, 49, 60, 61, 51, 47, 44, 35, 29]",교대역,223,을지로입구역,202,성수역,211,20251026,20260125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18553,7호선,보라매역,742,1,SUN,19,10,"[19, 19, 19, 20, 25, 23, 20, 16]",신대방삼거리역,741,건대입구역,727,석남역,761,20251026,20260125
18554,7호선,보라매역,742,1,SUN,19,20,"[21, 29, 29, 24, 28, 29, 27, 21]",신대방삼거리역,741,건대입구역,727,석남역,761,20251026,20260125
18555,7호선,보라매역,742,1,SUN,19,30,"[18, 15, 20, 22, 23, 25, 20, 16]",신대방삼거리역,741,건대입구역,727,석남역,761,20251026,20260125
18556,7호선,보라매역,742,1,SUN,19,40,"[18, 17, 24, 21, 19, 20, 21, 14]",신대방삼거리역,741,건대입구역,727,석남역,761,20251026,20260125
18557,7호선,보라매역,742,1,SUN,19,50,"[15, 18, 22, 25, 24, 27, 22, 16]",신대방삼거리역,741,건대입구역,727,석남역,761,20251026,20260125

In [4]:
'''
stationCode=222, updnline=1, dow=MON, hh=18, mm=00 필터링
'''
filtered_df = df[
    (df['subwayLine'] == '7호선') &
    # (df['stationCode'] == '222') &
    (df['updnLine'] == 1) &
    ((df['endStationName'] == '신풍역')| 
    (df['startStationName'] == '신풍역'))
    # (df['dow'] == 'MON') &
    # (df['hh'] == '18') &
    # (df['mm'] == '00')
]
filtered_df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,congestionCar,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
9516,7호선,대림역,744,1,MON,17,00,"[50, 42, 48, 47, 46, 48, 39, 32]",신풍역,743,신풍역,743,석남역,761,20251026,20260125
9517,7호선,대림역,744,1,MON,17,10,"[50, 56, 50, 48, 51, 49, 46, 35]",신풍역,743,신풍역,743,석남역,761,20251026,20260125
9518,7호선,대림역,744,1,MON,17,20,"[51, 51, 40, 47, 50, 49, 48, 40]",신풍역,743,신풍역,743,석남역,761,20251026,20260125
9519,7호선,대림역,744,1,MON,17,30,"[72, 78, 73, 67, 74, 66, 76, 55]",신풍역,743,신풍역,743,석남역,761,20251026,20260125
9520,7호선,대림역,744,1,MON,17,40,"[72, 75, 73, 70, 75, 84, 69, 65]",신풍역,743,신풍역,743,석남역,761,20251026,20260125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18475,7호선,보라매역,742,1,SUN,19,10,"[19, 19, 19, 20, 25, 23, 20, 16]",신대방삼거리역,741,장암역,709,신풍역,743,20251026,20260125
18476,7호선,보라매역,742,1,SUN,19,20,"[21, 29, 29, 24, 28, 29, 27, 21]",신대방삼거리역,741,장암역,709,신풍역,743,20251026,20260125
18477,7호선,보라매역,742,1,SUN,19,30,"[18, 15, 20, 22, 23, 25, 20, 16]",신대방삼거리역,741,장암역,709,신풍역,743,20251026,20260125
18478,7호선,보라매역,742,1,SUN,19,40,"[18, 17, 24, 21, 19, 20, 21, 14]",신대방삼거리역,741,장암역,709,신풍역,743,20251026,20260125
18479,7호선,보라매역,742,1,SUN,19,50,"[15, 18, 22, 25, 24, 27, 22, 16]",신대방삼거리역,741,장암역,709,신풍역,743,20251026,20260125

In [5]:
'''
df에서 df['subwayLine'] == '2호선'일때, (df['updnLine'] == 1) & (df['endStationName'] != '서울대입구역')만 남기기
df에서 df['subwayLine'] == '7호선'일때, (df['updnLine'] == 1) & ((df['endStationName'] != '신풍역')| (df['startStationName'] != '신풍역'))만 남기기
'''
scenario_df = df[(df['updnLine'] == 1)]
scenario_df = scenario_df[
    ~(
        ((df['subwayLine'] == '2호선') & (df['updnLine'] == 1) & ((df['endStationName'] == '서울대입구역') | (df['startStationName'] == '삼성역') | (df['endStationName'] == '삼성역'))) |
        ((df['subwayLine'] == '7호선') & (df['updnLine'] == 1) & ((df['endStationName'] == '신풍역') | (df['startStationName'] == '신풍역')))
    )
]
scenario_df

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_32136\1739569272.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  scenario_df = scenario_df[

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,congestionCar,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
12,2호선,강남역,222,1,MON,17,00,"[63, 72, 70, 70, 66, 76, 74, 79, 70, 40]",역삼역,221,성수역,211,홍대입구역,239,20251026,20260125
13,2호선,강남역,222,1,MON,17,10,"[93, 75, 90, 94, 99, 92, 96, 100, 76, 65]",역삼역,221,성수역,211,홍대입구역,239,20251026,20260125
14,2호선,강남역,222,1,MON,17,20,"[105, 92, 110, 124, 106, 101, 138, 108, 107, 79]",역삼역,221,성수역,211,홍대입구역,239,20251026,20260125
15,2호선,강남역,222,1,MON,17,30,"[81, 67, 80, 96, 87, 91, 91, 92, 74, 62]",역삼역,221,성수역,211,홍대입구역,239,20251026,20260125
16,2호선,강남역,222,1,MON,17,40,"[80, 94, 95, 100, 104, 92, 107, 94, 88, 66]",역삼역,221,성수역,211,홍대입구역,239,20251026,20260125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18553,7호선,보라매역,742,1,SUN,19,10,"[19, 19, 19, 20, 25, 23, 20, 16]",신대방삼거리역,741,건대입구역,727,석남역,761,20251026,20260125
18554,7호선,보라매역,742,1,SUN,19,20,"[21, 29, 29, 24, 28, 29, 27, 21]",신대방삼거리역,741,건대입구역,727,석남역,761,20251026,20260125
18555,7호선,보라매역,742,1,SUN,19,30,"[18, 15, 20, 22, 23, 25, 20, 16]",신대방삼거리역,741,건대입구역,727,석남역,761,20251026,20260125
18556,7호선,보라매역,742,1,SUN,19,40,"[18, 17, 24, 21, 19, 20, 21, 14]",신대방삼거리역,741,건대입구역,727,석남역,761,20251026,20260125
18557,7호선,보라매역,742,1,SUN,19,50,"[15, 18, 22, 25, 24, 27, 22, 16]",신대방삼거리역,741,건대입구역,727,석남역,761,20251026,20260125

In [6]:
scenario_df.to_csv('../../data/tmap_puzzle_filtering_car.csv', index=False, encoding='utf-8-sig')